//
//  ListInteractorTests.swift
//  ShuffleSongs
//
//  Created by Gilson Gil on 22/03/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ShuffleSongs

import Quick
import Nimble

final class ListInteractorSpec: QuickSpec {
  override func spec() {
    let sut = ListInteractor()

    describe("given an list interactor") {
      context("after fetch tracks list") {
        it("should have a list of tracks") {
          let request = List.TracksList.Request()
          expect(sut.list).to(beEmpty())
          sut.fetchList(request: request)
          waitUntil(timeout: 1) { finished in
            finished()
          }
          expect(sut.list).toNotEventually(beEmpty(), timeout: 5, pollInterval: 1, description: nil)
        }
      }
      context("after shuffling") {
        it("should have a different list of tracks") {
          let list = sut.list.compactMap { $0.identifier }
          sut.shuffle()
          expect(sut.list.compactMap { $0.identifier }).toNot(equal(list))
        }
      }
    }
  }
}
