//
//  ListPresenter.swift
//  ShuffleSongs
//
//  Created by Gilson Gil on 22/03/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
  func presentList(response: List.SongsList.Response)
}

final class ListPresenter: ListPresentationLogic {
  weak var viewController: ListDisplayLogic?

  // MARK: - Present List

  func presentList(response: List.SongsList.Response) {
    let viewModel = List.SongsList.ViewModel()
    viewController?.displayList(viewModel: viewModel)
  }
}
