//
//  ListPresenter.swift
//  ShuffleSongs
//
//  Created by Gilson Gil on 22/03/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic {
  func presentList(response: List.TracksList.Response)
}

final class ListPresenter: ListPresentationLogic {
  weak var viewController: ListDisplayLogic?

  // MARK: - Present List

  func presentList(response: List.TracksList.Response) {
    let list = response.list.compactMap(makeDisplayed)
    let viewModel = List.TracksList.ViewModel(list: list)
    viewController?.displayList(viewModel: viewModel)
  }

  private func makeDisplayed(track: Track) -> List.DisplayedTrack {
    let info = "\(track.artistName) (\(track.genre))"
    return List.DisplayedTrack(artworkUrl: track.artworkUrl, name: track.name, info: info)
  }
}
