//
//  ListWorker.swift
//  ShuffleSongs
//
//  Created by Gilson Gil on 22/03/19.
//  Copyright (c) 2019 Gilson Gil. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class ListWorker {
  func fetchList(artists: [Artist], completion: @escaping (() throws -> [Track]) -> Void) {
    var artistsIds = artists.reduce("") { $0 + String(describing: $1.identifier) + "," }
    artistsIds = String(artistsIds.prefix(artistsIds.count - 1))

    API.getTracksList(artistsIds: artistsIds, completion: completion)
  }

  func shuffle() {
  }
}
